# Generated by Django 2.2.4 on 2019-08-12 08:03

import app.test_api.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tabla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('superficie', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), app.test_api.validators.validate_number])),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
